###
POST http://localhost:8085/products/1/media
Accept: application/json
Content-Type: application/json

{
  "url": "0CAsQjRxqFwoTCIiGAdAD",
  "type": "1"
}

###
GET http://localhost:8085/products/2/media
Accept: application/json
